var n3={
	"title":"N3単語",
	"content":[
		{
			"word":"愛",
			"yomikata":"あい",
			"meaning":"爱，爱情",
			"id":"n30001"
		},
		{
			"word":"愛情",
			"yomikata":"あいじょう",
			"meaning":"爱情"
		},
		{
			"word":"アイス",
			"yomikata":"アイス",
			"meaning":"冰",
			"example":"アイスコーヒー"
		},
		{
			"word":"彼奴",
			"yomikata":"あいつ",
			"meaning":"那家伙"
		},
		{
			"word":"相手",
			"yomikata":"あいて",
			"meaning":"伙伴，同事，对手"
		},
		{
			"word":"アイデア／アイディア",
			"yomikata":"アイデア／アイディア",
			"meaning":"想法"
		},
		{
			"word":"生憎",
			"yomikata":"あいにく",
			"meaning":"不凑巧"
		},
		{
			"word":"曖昧",
			"yomikata":"あいまい",
			"meaning":"含糊不清，模棱两可"
		},
		{
			"word":"アイロン",
			"yomikata":"アイロン",
			"meaning":"熨斗",
			"example":"アイロンをかける"
		},
		{
			"word":"青空",
			"yomikata":"あおぞら",
			"meaning":"蓝天"
		},
		{
			"word":"赤字",
			"yomikata":"あかじ",
			"meaning":"赤字，亏空"
		},
		{
			"word":"明かり",
			"yomikata":"あかり",
			"meaning":"灯，光，希望"
		},
		{
			"word":"上がる",
			"yomikata":"あがる",
			"meaning":"上，登，上学，提高，长进"
		},
		{
			"word":"明らか",
			"yomikata":"あきらか",
			"meaning":"明显（二类形容词）"
		},
		{
			"word":"諦める",
			"yomikata":"あきらめる",
			"meaning":"放弃，死心"
		},
		{
			"word":"飽きる",
			"yomikata":"あきる",
			"meaning":"厌倦，厌烦"
		},
		{
			"word":"アクション",
			"yomikata":"アクション",
			"meaning":"动作，活动"
		},
		{
			"word":"アクセント",
			"yomikata":"アクセント",
			"meaning":"口音"
		},
		{
			"word":"欠伸",
			"yomikata":"あくび",
			"meaning":"哈欠"
		},
		{
			"word":"あける",
			"yomikata":"あける",
			"meaning":"天亮，新年伊始，时期结束"
		},
		{
			"word":"上げる",
			"yomikata":"あげる",
			"meaning":"举，抬，提高，增加"
		},
		{
			"word":"揚げる",
			"yomikata":"あげる",
			"meaning":"放，举起，油炸"
		},
		{
			"word":"憧れる",
			"yomikata":"あこがれる",
			"meaning":"憧憬"
		},
		{
			"word":"朝晩",
			"yomikata":"あさばん",
			"meaning":"早晚"
		},
		{
			"word":"朝日",
			"yomikata":"あさひ",
			"meaning":"旭日"
		},
		{
			"word":"朝飯",
			"yomikata":"あさめし",
			"meaning":"早饭",
			"example":"朝飯前：轻而易举"
		},
		{
			"word":"足音",
			"yomikata":"あしおと",
			"meaning":"脚步声"
		},
		{
			"word":"味見",
			"yomikata":"あじみ",
			"meaning":"尝味道"
		},
		{
			"word":"足元",
			"yomikata":"あしもと",
			"meaning":"脚下",
			"example":"足元の火がつく：大难临头"
		},
		{
			"word":"明日",
			"yomikata":"あす",
			"meaning":"明天"
		},
	]
};
var lecture17={
	"title":"第　17　課",
	"content":[
		{
			"word":"男尊女卑",
			"yomikata":"だんそんじょひ",
			"meaning":"男尊女卑",
		},{
			"word":"古い",
			"yomikata":"ふるい",
			"meaning":"陈旧的，古老的",
		},{
			"word":"威張る",
			"yomikata":"いばる",
			"meaning":"狂妄，逞威风",
		},{
			"word":"従順だ",
			"yomikata":"じゅうじゅんだ",
			"meaning":"顺从的",
		},{
			"word":"登場",
			"yomikata":"とうじょう",
			"meaning":"登场",
		},{
			"word":"終える",
			"yomikata":"おえる",
			"meaning":"结束",
		},{
			"word":"主人",
			"yomikata":"しゅじん",
			"meaning":"丈夫",
		},{
			"word":"飯",
			"yomikata":"めし",
			"meaning":"饭，食物",
		},{
			"word":"風呂",
			"yomikata":"ふろ",
			"meaning":"浴室",
		},{
			"word":"寝る",
			"yomikata":"ねる",
			"meaning":"睡觉",
		},{
			"word":"ご飯",
			"yomikata":"ごはん",
			"meaning":"饭",
		},{
			"word":"用意",
			"yomikata":"ようい",
			"meaning":"准备",
		},{
			"word":"入る",
			"yomikata":"はいる",
			"meaning":"进入",
		},{
			"word":"先に",
			"yomikata":"さきに",
			"meaning":"先",
		},{
			"word":"意味",
			"yomikata":"いみ",
			"meaning":"意义",
		},{
			"word":"馬鹿だ",
			"yomikata":"ばかだ",
			"meaning":"笨，愚蠢",
		},{
			"word":"でしゃばる",
			"yomikata":"でしゃばる",
			"meaning":"多嘴，放肆",
		},{
			"word":"場面",
			"yomikata":"ばめん",
			"meaning":"场面",
		},{
			"word":"一方",
			"yomikata":"いっぽう",
			"meaning":"一方面",
		},{
			"word":"奥さん",
			"yomikata":"おくさん",
			"meaning":"夫人",
		},{
			"word":"大人しい",
			"yomikata":"おとなしい",
			"meaning":"老实，和善",
		},{
			"word":"命令",
			"yomikata":"めいれい",
			"meaning":"命令",
		},{
			"word":"従う",
			"yomikata":"したがう",
			"meaning":"服从",
		},{
			"word":"可哀想だ",
			"yomikata":"かわいそうだ",
			"meaning":"可怜的",
		},{
			"word":"結婚",
			"yomikata":"けっこん",
			"meaning":"结婚",
		},{
			"word":"意見",
			"yomikata":"いけん",
			"meaning":"意见",
		},{
			"word":"世代",
			"yomikata":"せだい",
			"meaning":"一代，世代",
		},{
			"word":"価値観",
			"yomikata":"かちかん",
			"meaning":"价值观",
		},{
			"word":"全然",
			"yomikata":"ぜんぜん",
			"meaning":"全然，完全",
		},{
			"word":"違う",
			"yomikata":"ちがう",
			"meaning":"不同，错误",
		},{
			"word":"社会",
			"yomikata":"しゃかい",
			"meaning":"社会",
		},{
			"word":"続ける",
			"yomikata":"つづける",
			"meaning":"继续",
		},{
			"word":"普通",
			"yomikata":"ふつう",
			"meaning":"一般的，普通的",
		},{
			"word":"夫婦",
			"yomikata":"ふうふ",
			"meaning":"夫妇",
		},{
			"word":"共働き",
			"yomikata":"ともばたらき",
			"meaning":"夫妇共同工作",
		},{
			"word":"手伝う",
			"yomikata":"てつだう",
			"meaning":"帮助，帮忙",
		},{
			"word":"スーパー",
			"yomikata":"スーパー",
			"meaning":"超市",
		},{
			"word":"買い物",
			"yomikata":"かいもの",
			"meaning":"购物",
		},{
			"word":"くれる",
			"yomikata":"くれる",
			"meaning":"给我",
		},{
			"word":"連れる",
			"yomikata":"つれる",
			"meaning":"带领",
		},{
			"word":"今日",
			"yomikata":"きょう",
			"meaning":"今天",
		},{
			"word":"込む",
			"yomikata":"こむ",
			"meaning":"拥挤",
		},{
			"word":"練習",
			"yomikata":"れんしゅう",
			"meaning":"练习",
		},{
			"word":"つまらない",
			"yomikata":"つまらない",
			"meaning":"无聊，没意思",
		},{
			"word":"ねえ",
			"yomikata":"ねえ",
			"meaning":"喂",
		},{
			"word":"今晩",
			"yomikata":"こんばん",
			"meaning":"今天晚上",
		},{
			"word":"カレー",
			"yomikata":"カレー",
			"meaning":"咖喱",
		},{
			"word":"外",
			"yomikata":"そと",
			"meaning":"外边",
		},{
			"word":"出す",
			"yomikata":"だす",
			"meaning":"放出",
		},{
			"word":"行っていらっしゃい",
			"yomikata":"いっていらしゃい",
			"meaning":"您走好，一路顺风",
		},{
			"word":"早い",
			"yomikata":"はやい",
			"meaning":"早的",
		},
	]
};